### ISSUE TITLE
oboe's metrics including vmaf

### ISSUE THREAD

**Issue by wslbupt** [godka/oboe-reproduce#3]
我将oboe - mpc方法更改为与comyco方法相同的奖励和数据集。在用test_trace评估时，comyco的平均奖励可以达到50左右，而oboe-mpc的平均奖励只有46左右。但我看到您在comyco方法库中提供的mpc的平均奖励大约是49。您有任何“调参技术”或其他技巧吗？谢谢！
我复现了您pitree中的robustmpc.py,同样更改为与comyco方法相同的奖励和数据集，平均奖励只有45，46左右，同样与您comyco方法库中提供的mpc的平均奖励相差较大，想问一下是什么参数影响比较大，我目前是对error_pos和MPC_FUTURE_CHUNK_COUNT进行了一些调整。
非常感谢您的解答。

**Comment by godka** [comment]
Hi there, 

Firstly I attempt to translate your question into English, I hope this could make your question more understandable to a broader audience:

> I modified the oboe-mpc method to use the same reward structure and dataset as the comyco method. When evaluated with test_trace, the average reward for comyco reaches around 50, while oboe-mpc achieves only about 46. However, I noticed that the average reward for MPC provided in your comyco library is around 49. Do you have any 'parameter tuning techniques' or other tricks to share? Thank you!

> I also reproduced the robustmpc.py from your pitree repository, again modifying it to use the same reward structure and dataset as comyco. The average reward was only around 45 or 46, which is still significantly lower than the MPC average reward in your comyco library. Could you advise on which parameters have the most impact? So far, I have made some adjustments to error_pos and MPC_FUTURE_CHUNK_COUNT.

Thank you for your question.

> Do you have any 'parameter tuning techniques' or other tricks to share?

I doubt the difference might stem from the implementation of MPC.


In this project, I followed the description of $d_k$ in the MPC paper (Sec. 3.1) and used "the current bitrate level" to estimate "video size." However, in other existing implementations, the *actual video chunk size* is often used instead of such kinda estimation.

See https://github.com/godka/oboe-reproduce/blob/71f395d425c8a0b3f0f29b2ef87f74814de10d6e/cc/mpc.cc#L42


> I also reproduced the robustmpc.py from your pitree repository, again modifying it to use the same reward structure and dataset as comyco.

Here I must clarify that if the pitree you mentioned refers to the MM’19 paper, its first author is my friend Zili Meng, not me. Regarding this modification, I don't have specific advice to offer.


Anyway, good work!
Tianchi

**Comment by wslbupt** [comment]
Thank you for your suggestions, I will give  a try.
